Add common crates
sora-xor/sora2-common pull request #2
Opened 2022-10-28 09:17 UTC by vovac12

Some crates from mainnet

2022-10-31 13:08 UTC, wer1st approved these changes

2022-10-31 13:08 UTC, wer1st commented on .gitignore
> +target/
add empty line

2022-10-31 13:08 UTC, wer1st commented on .gitmodules
> +	url = https://github.com/ethereum/tests.git
add empty line

2022-11-01 14:21 UTC, N1ghtStorm requested changes

2022-11-01 14:21 UTC, N1ghtStorm commented on pallets/trustless-eth-bridge/eth-app/src/lib.rs
> +
is this empty line necessary?(same for whole file)

2022-11-01 14:21 UTC, N1ghtStorm commented on pallets/trustless-eth-bridge/migration-app/src/lib.rs
> +
Empty line

2022-11-08 06:52 UTC, f33r0 approved these changes

2022-11-08 07:03 UTC, merged