[DOPS-2702] update clippy workflow
sora-xor/sora2-common pull request #56
Opened 2023-08-22 11:54 UTC by f33r0

# Task

[DOPS-2702] update clippy workflow

## Changes

1. Using lib
2. Added clippy workflow

## Author

Signed-off-by: name <zaporozhets@soramitsu.co.jp>

[DOPS-2702]: https://soramitsu.atlassian.net/browse/DOPS-2702

2023-08-23 06:26 UTC, wpi86 requested changes

2023-08-23 06:26 UTC, wpi86 commented on Jenkinsfile
> +      codeCoverage: false
why?

2023-08-25 06:59 UTC, Cre-eD approved these changes

2023-08-25 07:36 UTC, wpi86 approved these changes

2023-08-25 08:07 UTC, merged